apiVersion: 1

datasources:
  - name: Prometheus
    uid: metrics
    type: prometheus
    url: http://prometheus:9090
    editable: true
    isDefault: true
    jsonData:
      exemplarTraceIdDestinations:
        - datasourceUid: traces
          name: trace_id
        - url: http://jaeger:16686/jaeger/ui/trace/$${__value.raw}
          name: trace_id
          urlDisplayLabel: View in Jaeger UI