<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <AssemblyName>SpaceEngineers.Core.Basics.Test</AssemblyName>
        <RootNamespace>SpaceEngineers.Core.Basics.Test</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="coverlet.msbuild" />
        <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" />
        <PackageReference Include="StyleCop.Analyzers" />
        <PackageReference Include="xunit" />
        <PackageReference Include="xunit.runner.visualstudio" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\..\src\Common\Basics\Basics.csproj"/>
    </ItemGroup>
</Project>