<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>SpaceEngineers.Core.Basics.Test</AssemblyName>
        <RootNamespace>SpaceEngineers.Core.Basics.Test</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\..\..\src\Common\Basics\Basics.csproj"/>
        <ProjectReference Include="..\..\..\src\Common\Basics.SourceGenerators\Basics.SourceGenerators.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false" />
    </ItemGroup>
</Project>