<Project>
    <PropertyGroup>
        <!--general info-->
        <Authors>Nikita Grishin</Authors>
        <Company>MightyMorphinSpaceEngineers</Company>
        <Copyright>Copyright (c) 2025</Copyright>
        <RepositoryType>git</RepositoryType>
        <RepositoryUrl>https://github.com/warning-explosive/Core</RepositoryUrl>

        <!--roslyn analysis-->
        <RunAnalyzers>true</RunAnalyzers>
        <RunAnalyzersDuringBuild>true</RunAnalyzersDuringBuild>
        <RunAnalyzersDuringLiveAnalysis>true</RunAnalyzersDuringLiveAnalysis>
        <NoWarn>
            $(NoWarn);
            CS1591;
            SA1000;
            SA1009;
            SA1010;
            SA1101;
            SA1106;
            SA1124;
            SA1204;
            SA1309;
            SA1413;
            SA1600;
            SA1601;
            SA1602;
            SA1629;
            SA1633;
            AD0001;
            xUnit1030;
        </NoWarn>

        <!--generate on build-->
        <AutoGenerateBindingRedirects>true</AutoGenerateBindingRedirects>
        <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
        <GenerateDocumentationFile>true</GenerateDocumentationFile>
        <EnableRequestDelegateGenerator>true</EnableRequestDelegateGenerator>

        <!--nuget packagees-->
        <IsPackable>false</IsPackable>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>

        <!--debug symbols-->
        <DebugSymbols>true</DebugSymbols>
        <DebugType>full</DebugType>

        <!--other-->
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <ImplicitUsings>enable</ImplicitUsings>
        <TieredCompilation>true</TieredCompilation>
        <InvariantGlobalization>true</InvariantGlobalization>
        <!-- <PublishTrimmed>true</PublishTrimmed> - it has issues with json serialization -->
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.CodeAnalysis.Analyzers" />
        <PackageReference Include="Microsoft.CodeAnalysis.NetAnalyzers" />
        <PackageReference Include="StyleCop.Analyzers" />
    </ItemGroup>
</Project>