version: '3'
services:
  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=Password12!
    ports:
      - '5432:5432'
  rabbit:
    image: rabbitmq:3-management
    restart: unless-stopped
    ports:
      - '15672:15672'
      - '5672:5672'
  web-app:
    depends_on:
      - postgres
      - rabbit
    build:
      dockerfile: Dockerfile.webtest
      context: .
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - '5000:80'