ARG DOT_NET_VERSION=7.0

FROM mcr.microsoft.com/dotnet/sdk:${DOT_NET_VERSION} AS builder
ENV NUGET_XMLDOC_MODE=none
WORKDIR /build
COPY . .
RUN dotnet restore Tests/Test.WebApplication/Test.WebApplication.csproj --no-cache -v:minimal
RUN dotnet build Tests/Test.WebApplication/Test.WebApplication.csproj -c Debug -o out --no-cache --no-restore -v:minimal

FROM mcr.microsoft.com/dotnet/aspnet:${DOT_NET_VERSION}
WORKDIR /app
COPY --from=builder /build/out /app
COPY --from=builder /build/Tests/Test.WebApplication/ComposeSettings /app/Settings
COPY --from=builder /build/Tests/Test.WebApplication/Test.WebApplication.csproj /app/Test.WebApplication.csproj
ENTRYPOINT ["dotnet", "SpaceEngineers.Core.Test.WebApplication.dll"]