# SDK_ARCH = arm64v8 | amd64
ARG SDK_ARCH=arm64v8
ARG DOT_NET_VERSION=7.0

FROM mcr.microsoft.com/dotnet/sdk:${DOT_NET_VERSION}-alpine-${SDK_ARCH} AS builder
ENV NUGET_XMLDOC_MODE=none
WORKDIR /build

# separate restore layer
COPY ["./*.csproj", "./*/*.csproj", "./*/*/*.csproj", "./*.sln", "./*.sh", "./*.config", "./"]
RUN chmod +x restore_project_structure.sh
RUN ./restore_project_structure.sh
RUN dotnet restore Tests/Test.WebApplication/Test.WebApplication.csproj --packages ./packages --no-cache -v:minimal

# separate build layer
COPY . .
RUN dotnet build Tests/Test.WebApplication/Test.WebApplication.csproj -c Debug -o out --packages ./packages --no-cache -v:minimal

FROM mcr.microsoft.com/dotnet/aspnet:${DOT_NET_VERSION}-alpine
WORKDIR /app
COPY --from=builder /build/out /app
COPY --from=builder /build/Tests/Test.WebApplication/ComposeSettings /app/Settings
COPY --from=builder /build/Tests/Test.WebApplication/Test.WebApplication.csproj /app/Test.WebApplication.csproj
ENTRYPOINT ["dotnet", "SpaceEngineers.Core.Test.WebApplication.dll"]

# docker buildx build --platform linux/amd64,linux/arm64 -f Dockerfile.webtest .
