version: '3'
services:
  postgres:
    image: postgres:15.1-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=Password12!
    ports:
      - '5432:5432'
  rabbit:
    image: rabbitmq:3.11.11-management-alpine
    restart: unless-stopped
    ports:
      - '15672:15672'
      - '5672:5672'
  jaeger:
    image: jaegertracing/all-in-one:1.43.0
    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true
    ports:
      - 6831:6831/udp # accept jaeger.thrift over Thrift-compact protocol
      - 6832:6832/udp # accept jaeger.thrift over Thrift-binary protocol
      - 5778:5778 # serve configs (sampling, etc.)
      - 16686:16686 # serve frontend
      - 4317:4317 # accept OpenTelemetry Protocol (OTLP) over gRPC, if enabled
      - 4318:4318 # accept OpenTelemetry Protocol (OTLP) over HTTP, if enabled
      - 14250:14250 # accept model.proto
      - 14268:14268 # accept jaeger.thrift directly from clients
      - 14269:14269 # ???
      - 9411:9411 # Zipkin compatible endpoint (optional)
  web-app:
    depends_on:
      - postgres
      - rabbit
      - jaeger
    build:
      dockerfile: Dockerfile.webtest
      context: .
    restart: unless-stopped
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - '5000:80'