<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
    <PropertyGroup>
        <AssemblyName>SpaceEngineers.Core.Basics</AssemblyName>
        <RootNamespace>SpaceEngineers.Core.Basics</RootNamespace>
    </PropertyGroup>
    <ItemGroup>
        <ProjectReference Include="..\Basics.SourceGenerators\Basics.SourceGenerators.csproj"
                          OutputItemType="Analyzer"
                          ReferenceOutputAssembly="false" />
    </ItemGroup>
</Project>