{
 "title": "Prometheus overview",
 "description": "Prometheus overview",
 "tags": [ "prometheus" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  { "title": "Prometheus overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Targets state",
   "type": "stat",
   "description": "State of the scrape targets",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bool_on_off" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Series number",
   "type": "stat",
   "description": "Number of stored time series",
   "gridPos": { "h": 5, "w": 7, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "prometheus_tsdb_head_series", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Samples",
   "type": "stat",
   "description": "Number of the scraped samples",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "sum(scrape_samples_scraped)", "legendFormat": "Total" },
    { "expr": "scrape_samples_scraped", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Scrape duration",
   "type": "bargauge",
   "description": "Scrape duration",
   "gridPos": { "h": 15, "w": 7, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "scrape_duration_seconds * 1000", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Last scrape",
   "type": "gauge",
   "description": "Time passed from the last scrape",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "time() - timestamp(scrape_duration_seconds)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Average CPU time",
   "type": "gauge",
   "description": "Average user and system CPU time spent",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total[5m]) * 1000",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Process resident memory",
   "type": "gauge",
   "description": "Process resident memory",
   "gridPos": { "h": 5, "w": 17, "x": 7, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "process_resident_memory_bytes / 1024 / 1024",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}