{
 "title": "Postgres overview",
 "tags": [ "postgresql" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Server",
    "query": {
     "query": "label_values(pg_settings_value, server)"
    }
   },
   {
    "name": "Database",
    "query": {
     "query": "label_values(pg_statements_rows{server=~\"$Server\"}, database)"
    }
   },
   {
    "name": "Schema",
    "query": {
     "query": "label_values(pg_tables_rows{server=~\"$Server\",database=~\"$Database\"}, schema)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Server version",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_settings_value{server=~\"$Server\",name=\"server_version\"}",
     "legendFormat": "Server version"
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "stat",
   "description": "/proc/loadavg - one",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_loadavg_one{server=~\"$Server\"}",
     "legendFormat": "CPU utilization"
    }
   ]
  },
  {
   "title": "Disk utilization",
   "type": "stat",
   "description": "/proc/diskstats - weighted_time_spent_doing_io",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(pg_diskstats_weighted_time_spent_doing_io{server=~\"$Server\"}[$__rate_interval])",
     "legendFormat": "Disk utilization"
    }
   ]
  },
  {
   "title": "htop memory",
   "type": "timeseries",
   "description": "htop memory usage: green - used memory; blue - buffered memory; yellow - cached memory",
   "gridPos": { "h": 10, "w": 7, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_meminfo_value{server=~\"$Server\",measure=\"MemTotal\"}",
     "legendFormat": "MemTotal"
    },
    {
     "expr": "pg_meminfo_value{server=~\"$Server\",measure=\"MemFree\"}",
     "legendFormat": "MemFree"
    },
    {
     "expr": "pg_meminfo_value{server=~\"$Server\",measure=\"Buffers\"}",
     "legendFormat": "Buffers"
    },
    {
     "expr": "pg_meminfo_value{server=~\"$Server\",measure=\"Cached\"}",
     "legendFormat": "Cached"
    },
    {
     "expr": "pg_meminfo_value{server=~\"$Server\",measure=\"SwapTotal\"}",
     "legendFormat": "SwapTotal"
    },
    {
     "expr": "pg_meminfo_value{server=~\"$Server\",measure=\"SwapFree\"}",
     "legendFormat": "SwapFree"
    },
    {
     "expr": "pg_meminfo_value{server=~\"$Server\",measure=\"SReclaimable\"}",
     "legendFormat": "SReclaimable"
    },
    {
     "expr": "pg_meminfo_value{server=~\"$Server\",measure=\"Shmem\"}",
     "legendFormat": "Shmem"
    }
   ]
  },
  {
   "title": "Disk I/O",
   "type": "timeseries",
   "description": "/proc/diskstats - serctors read/written",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(pg_diskstats_bytes_read{server=~\"$Server\"}[$__rate_interval])",
     "legendFormat": "Read"
    },
    {
     "expr": "rate(pg_diskstats_bytes_written{server=~\"$Server\"}[$__rate_interval])",
     "legendFormat": "Write"
    }
   ]
  },
  {
   "title": "Up-time",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - pg_postmaster_start_time_seconds{server=~\"$Server\"}",
     "legendFormat": "Up-time"
    }
   ]
  },
  {
   "title": "Replication lag",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_replication_lag{server=~\"$Server\"}",
     "legendFormat": "Replication lag"
    }
   ]
  },
  {
   "title": "Virtual memory size",
   "type": "gauge",
   "description": "/proc/{pid}/status - VmSize",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "pg_status_value{server=~\"$Server\",measure=\"VmSize\"}",
     "legendFormat": "VmSize"
    }
   ]
  },
  {
   "title": "Database",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connections",
     "type": "stat",
     "gridPos": { "h": 5, "w": 6, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (database)(pg_connection_state_count{server=~\"$Server\",database=~\"$Database\"})",
       "legendFormat": "Total"
      },
      {
       "expr": "sum by (database)(pg_connection_state_count{server=~\"$Server\",database=~\"$Database\",state=\"active\"})",
       "legendFormat": "Active"
      },
      {
       "expr": "sum by (database)(pg_connection_state_count{server=~\"$Server\",database=~\"$Database\",state=\"idle\"})",
       "legendFormat": "Idle"
      },
      {
       "expr": "sum by (database)(pg_connection_state_count{server=~\"$Server\",database=~\"$Database\",state!~\"active|idle\"})",
       "legendFormat": "Other"
      }
     ]
    },
    {
     "title": "Buffer cache hits ratio",
     "type": "stat",
     "gridPos": { "h": 5, "w": 3, "x": 6, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "rate(pg_stat_database_blks_hit{server=~\"$Server\",database=~\"$Database\"}[$__rate_interval])\n/ (rate(pg_stat_database_blks_hit{server=~\"$Server\",database=~\"$Database\"}[$__rate_interval])\n   + rate(pg_stat_database_blks_read{server=~\"$Server\",database=~\"$Database\"}[$__rate_interval]))",
       "legendFormat": "Buffer cache hits ratio"
      }
     ]
    },
    {
     "title": "Affected rows",
     "type": "stat",
     "gridPos": { "h": 5, "w": 15, "x": 9, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "increase(pg_stat_database_tup_returned{server=~\"$Server\",database=~\"$Database\"}[$__range])\n+ increase(pg_stat_database_tup_fetched{server=~\"$Server\",database=~\"$Database\"}[$__range])\n+ increase(pg_stat_database_tup_inserted{server=~\"$Server\",database=~\"$Database\"}[$__range])\n+ increase(pg_stat_database_tup_updated{server=~\"$Server\",database=~\"$Database\"}[$__range])\n+ increase(pg_stat_database_tup_deleted{server=~\"$Server\",database=~\"$Database\"}[$__range])",
       "legendFormat": "Total"
      },
      {
       "expr": "increase(pg_stat_database_tup_returned{server=~\"$Server\",database=~\"$Database\"}[$__range])\n+ increase(pg_stat_database_tup_fetched{server=~\"$Server\",database=~\"$Database\"}[$__range])",
       "legendFormat": "Read"
      },
      {
       "expr": "+ increase(pg_stat_database_tup_inserted{server=~\"$Server\",database=~\"$Database\"}[$__range])",
       "legendFormat": "Inserted"
      },
      {
       "expr": "increase(pg_stat_database_tup_updated{server=~\"$Server\",database=~\"$Database\"}[$__range])",
       "legendFormat": "Updated"
      },
      {
       "expr": "increase(pg_stat_database_tup_deleted{server=~\"$Server\",database=~\"$Database\"}[$__range])",
       "legendFormat": "Deleted"
      }
     ]
    },
    {
     "title": "Deadlocks",
     "type": "stat",
     "description": "Total amount of deadlocks within specified range",
     "gridPos": { "h": 5, "w": 3, "x": 0, "y": 17 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum by (datname)(increase(pg_stat_database_deadlocks{server=~\"$Server\",database=~\"$Database\"}[$__range]))",
       "legendFormat": "Deadlocks"
      }
     ]
    },
    {
     "title": "Locks",
     "type": "table",
     "description": "Detailed information about actually locked statements",
     "gridPos": { "h": 5, "w": 21, "x": 3, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "time() - pg_locks_blocked_time{server=~\"$Server\",database=~\"$Database\"}",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Statements",
     "type": "table",
     "description": "select\n    r.rolname as username,\n    d.datname as database,\n    s.query,\n    p.plan\nfrom pg_stat_statements s, pg_store_plans p, pg_roles r, pg_database d\nwhere s.queryid = p.queryid\n  and s.userid = r.oid\n  and s.dbid = d.oid\n  and s.queryid = _queryid_",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "sum by (queryid)(increase(pg_statements_rows{server=~\"$Server\",database=~\"$Database\"}[$__range]))",
       "legendFormat": "Affected Rows"
      },
      {
       "expr": "sum by (queryid)(increase(pg_statements_calls{server=~\"$Server\",database=~\"$Database\"}[$__range]))",
       "legendFormat": "Calls"
      },
      {
       "expr": "avg by (queryid)(increase(pg_statements_plans{server=~\"$Server\",database=~\"$Database\"}[$__range]))",
       "legendFormat": "Plans"
      },
      {
       "expr": "avg by (queryid)(pg_statements_mean_exec_time{server=~\"$Server\",database=~\"$Database\"})",
       "legendFormat": "Mean execution time"
      },
      {
       "expr": "avg by (queryid)(pg_statements_max_exec_time{server=~\"$Server\",database=~\"$Database\"})",
       "legendFormat": "Max execution time"
      },
      {
       "expr": "avg by (queryid)(pg_statements_mean_plan_time{server=~\"$Server\",database=~\"$Database\"})",
       "legendFormat": "Mean plan time"
      },
      {
       "expr": "avg by (queryid)(pg_statements_max_plan_time{server=~\"$Server\",database=~\"$Database\"})",
       "legendFormat": "Max plan time"
      }
     ]
    }
   ]
  },
  { "title": "Schema", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Objects",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "pg_tables_rows{server=~\"$Server\",database=~\"$Database\",schema=~\"$Schema\"}",
     "legendFormat": "Rows"
    },
    {
     "expr": "pg_tables_table_bytes{server=~\"$Server\",database=~\"$Database\",schema=~\"$Schema\"}",
     "legendFormat": "Table size"
    },
    {
     "expr": "pg_tables_index_bytes{server=~\"$Server\",database=~\"$Database\",schema=~\"$Schema\"}",
     "legendFormat": "Index size"
    },
    {
     "expr": "rate(pg_tables_read_from_disk{server=~\"$Server\",database=~\"$Database\",schema=~\"$Schema\"}[$__rate_interval])",
     "legendFormat": "Disk hits"
    },
    {
     "expr": "rate(pg_tables_read_from_cache{server=~\"$Server\",database=~\"$Database\",schema=~\"$Schema\"}[$__rate_interval])",
     "legendFormat": "Cache hits"
    }
   ]
  }
 ]
}