MongoClientSettings:
  AllowInsecureTls: false
  ApplicationName: 
  Compressors: []
  ClusterConfigurator: 
  ConnectionMode: Automatic
  ConnectTimeout: 00:00:30
  Credential: 
  Credentials: []
  GuidRepresentation: CSharpLegacy
  IsFrozen: false
  HeartbeatInterval: 00:00:10
  HeartbeatTimeout: -00:00:00.0010000
  IPv6: false
  LocalThreshold: 00:00:00.0150000
  MaxConnectionIdleTime: 00:10:00
  MaxConnectionLifeTime: 00:30:00
  MaxConnectionPoolSize: 25
  MinConnectionPoolSize: 1
  ReadConcern:
    IsServerDefault: true
    Level: 
  ReadEncoding: 
  ReadPreference:
    MaxStaleness: 
    ReadPreferenceMode: Primary
    TagSets: []
  ReplicaSetName: 
  RetryReads: true
  RetryWrites: true
  Scheme: MongoDB
  SdamLogFilename: 
  Server:
    Host: localhost
    Port: 27017
  Servers:
  - Host: localhost
    Port: 27017
  ServerSelectionTimeout: 00:00:30
  SocketTimeout: 00:00:00
  SslSettings: 
  UseSsl: false
  UseTls: false
  VerifySslCertificate: true
  WaitQueueSize: 2147483647
  WaitQueueTimeout: 00:01:00
  WriteConcern:
    FSync: 
    IsAcknowledged: true
    IsServerDefault: true
    Journal: 
    W: 
    WTimeout: 
  WriteEncoding: 
