Int: 1
Decimal: 42.42
String: Hello world!
Date: 0001-01-01T00:00:00.0000000
Reference:
  Int: 1
  Decimal: 42.42
  String: Hello world!
  Date: 0001-01-01T00:00:00.0000000
  Reference: 
  Collection: 
  Dictionary: 
Collection:
- Int: 1
  Decimal: 42.42
  String: Hello world!
  Date: 0001-01-01T00:00:00.0000000
  Reference: 
  Collection: 
  Dictionary: 
Dictionary:
  First:
    Int: 1
    Decimal: 42.42
    String: Hello world!
    Date: 0001-01-01T00:00:00.0000000
    Reference: 
    Collection: 
    Dictionary: 
