{
 "title": "OpenTelemetry collector",
 "description": "otelcol metrics dashboard",
 "tags": [ "opentelemetry" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "service_version",
    "label": "service_version",
    "query": {
     "query": "query_result(sum(otelcol_process_uptime{}) by (service_version))\n"
    }
   }
  ]
 },
 "panels": [
  { "title": "Process", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Instances",
   "type": "stat",
   "description": "Number of Otel Collector instances",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(count(otelcol_process_cpu_seconds{service_instance_id=~\".*\"}) by (service_instance_id))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Up-time",
   "type": "stat",
   "description": "Time passed from the process start",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "otelcol_process_uptime", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Average CPU time",
   "type": "gauge",
   "description": "Average user and system CPU time spent",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(otelcol_process_cpu_seconds[$__range])\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "description": "Process physical memory",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "otelcol_process_memory_rss", "legendFormat": "{{label_name}}" }
   ]
  },
  { "title": "Trace Pipeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Refused",
   "type": "stat",
   "description": "Number of spans that could not be pushed into the pipeline",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(otelcol_receiver_refused_spans) by (service_instance_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sending errors",
   "type": "stat",
   "description": "Number of spans failed to be added to the sending queue\n+\nNumber of spans in failed attempts to send to destination",
   "gridPos": { "h": 8, "w": 5, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(otelcol_exporter_enqueue_failed_spans + otelcol_exporter_send_failed_spans) by (service_instance_id)",
     "legendFormat": "Enqueue"
    },
    {
     "expr": "sum(otelcol_exporter_send_failed_spans) by (service_instance_id)",
     "legendFormat": "Send"
    }
   ]
  },
  {
   "title": "Sent",
   "type": "stat",
   "description": "Number of spans successfully sent to destination",
   "gridPos": { "h": 8, "w": 3, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(otelcol_exporter_sent_spans) by (service_instance_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Lost",
   "type": "stat",
   "description": "Number of spans lost within pipeline due to refuse or some inner errors",
   "gridPos": { "h": 8, "w": 3, "x": 11, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(otelcol_receiver_accepted_spans + otelcol_receiver_refused_spans) by (service_instance_id)\n-\nsum(otelcol_exporter_sent_spans) by (service_instance_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accepted",
   "type": "stat",
   "description": "Number of spans successfully pushed into the pipeline",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(otelcol_receiver_accepted_spans) by (service_instance_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Metrics Pipeline", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Refused",
   "type": "stat",
   "description": "Number of metric points that could not be pushed into the pipeline",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(otelcol_receiver_refused_metric_points) by (service_instance_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sending errors",
   "type": "stat",
   "description": "Number of metric points failed to be added to the sending queue\n+\nNumber of metric points in failed attempts to send to destination",
   "gridPos": { "h": 7, "w": 5, "x": 3, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(otelcol_exporter_enqueue_failed_metric_points) by (service_instance_id)",
     "legendFormat": "Enqueue"
    },
    {
     "expr": "sum(otelcol_exporter_send_failed_metric_points) by (service_instance_id)",
     "legendFormat": "Send"
    }
   ]
  },
  {
   "title": "Sent",
   "type": "stat",
   "description": "Number of metric points successfully sent to destination",
   "gridPos": { "h": 8, "w": 3, "x": 8, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(otelcol_exporter_sent_metric_points) by (service_instance_id)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Accepted",
   "type": "stat",
   "description": "Number of metric points successfully pushed into the pipeline",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(otelcol_receiver_accepted_metric_points) by (service_instance_id)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}