name: build-test-publish
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v3
    - name: setup .net toolchain
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: restore packages
      run: dotnet restore --no-cache --verbosity minimal
    - name: build solution
      run: dotnet build -c Debug --no-restore --verbosity minimal
    - name: run tests
      run: dotnet test --no-build --verbosity minimal
